import { Theme } from './types';

export const I18N = {
  zh: {
    app_assistant: '万象助手', 
    app_settings: '系统设置',
    app_store: '应用商店',
    app_worldbook: '万象书', 
    
    set_conn: '连接',
    set_anchor: '锚点', 
    set_theme: '主题', 
    set_profile: '档案',
    set_about: '关于',
    
    conn_title: '神经连接 (Neural Link)',
    conn_provider: '核心协议',
    conn_endpoint: '服务端点 (Endpoint)',
    conn_key: '访问密钥 (API Key)',
    conn_model: '模型标识 (Model ID)',
    conn_gemini_rec: '推荐: gemini-2.5-flash',
    conn_openai_desc: '兼容 OpenAI / DeepSeek / LocalAI',
    
    ast_config_title: '助手内核配置',
    ast_name: '助手标识',
    ast_avatar: '视觉形态 (URL)',
    ast_prompt: '核心逻辑 (System Prompt)',
    ast_greeting: '唤醒语',
    ast_save_tip: '配置已更新',
    
    cmd_menu_title: '快捷指令',
    cmd_analyze: '当前世界分析',
    cmd_status: '终端状态自检',
    cmd_help: '操作指南',
    cmd_story: '剧情回顾',

    theme_simple: '简',
    theme_dao: '道',
    theme_night: '夜',
    theme_lang_switch: '语言 / Language',
    theme_installed: '已安装主题',
    theme_import: '导入 UI',
    theme_tpl: '下载模板',

    back: '返回',
    save: '保存',
    delete: '删除',
    create: '新建',
    import: '导入',
    export: '导出',
    online: '运行中',
    typing: '计算中...',
    summarizing: '正在整理记忆...',
    no_signal: '(无信号)',
    sys_tip_key: '(系统提示: 请在设置中配置 API Key)',
    
    msg_placeholder: '输入指令...',
    img_upload_title: '视觉输入 (Gemini)',
    img_attached: '图像已捕获',
    summary_label: '历史记忆摘要',
    
    profile_lock_title: '全局档案覆盖',
    profile_lock_desc: '启用后，将强制使用下方档案作为所有世界的玩家设定。关闭则使用世界书自带设定。',
    ph_name: '姓名 / 昵称',
    ph_avatar: '头像链接 (URL)',
    ph_gender: '性别',
    ph_age: '年龄',
    ph_bio: '喜好 / 备注',

    wb_home_desc: '当前世界概览',
    wb_btn_switch: '切换',
    wb_btn_meta: '信息',
    wb_btn_char: '角色',
    wb_btn_world: '设定',
    
    wb_switch_title: '世界书管理',
    wb_new_world: '新建空白世界',
    wb_del_confirm: '确定要删除这个世界书吗？此操作不可逆。',
    wb_export_world: '导出世界书',
    wb_import_world: '导入世界书',
    
    wb_char_player_mode: '玩家设定模式',
    wb_char_use_global: '正在使用全局个人档案',
    wb_char_use_local: '正在使用当前世界独立设定',
    
    wb_meta_name: '世界名称',
    wb_meta_tags: '标签 (TAGs)',
    wb_meta_desc: '世界简介',
    
    wb_char_ai_title: '世界NPC (仅作记录)',
    wb_char_pl_title: '玩家设定 (Player)',
    
    store_offline: '商店暂未开放',
    import_success: '导入成功！',
    import_error: '格式错误：请确认文件符合万象书标准 (metadata/world/character)',
    
    about_title: '万界终端',
    about_ver: 'v0.5.0 (Beta)',
    about_date: '2025.05.20',
  },
  en: {
    app_assistant: 'OmniLink',
    app_settings: 'Settings',
    app_store: 'Store',
    app_worldbook: 'OmniBook',

    set_conn: 'Connect',
    set_anchor: 'Anchor',
    set_theme: 'Theme',
    set_profile: 'Profile',
    set_about: 'About',

    conn_title: 'Neural Link',
    conn_provider: 'Protocol',
    conn_endpoint: 'Endpoint',
    conn_key: 'API Key',
    conn_model: 'Model ID',
    conn_gemini_rec: 'Rec: gemini-2.5-flash',
    conn_openai_desc: 'OpenAI Compatible',

    ast_config_title: 'Core Configuration',
    ast_name: 'Name',
    ast_avatar: 'Avatar URL',
    ast_prompt: 'Core Logic',
    ast_greeting: 'Greeting',
    ast_save_tip: 'Config Updated',

    cmd_menu_title: 'Commands',
    cmd_analyze: 'Analyze World',
    cmd_status: 'System Check',
    cmd_help: 'User Guide',
    cmd_story: 'Recap Story',

    theme_simple: 'Simple',
    theme_dao: 'Dao',
    theme_night: 'Night',
    theme_lang_switch: 'Language / 语言',
    theme_installed: 'Installed Themes',
    theme_import: 'Import UI',
    theme_tpl: 'Template',

    back: 'Back',
    save: 'Save',
    delete: 'Delete',
    create: 'Create',
    import: 'Import',
    export: 'Export',
    online: 'Online',
    typing: 'Computing...',
    summarizing: 'Summarizing Memory...',
    no_signal: '(No Signal)',
    sys_tip_key: '(System: API Key missing)',

    msg_placeholder: 'Enter command...',
    img_upload_title: 'Visual Input',
    img_attached: 'Image Captured',
    summary_label: 'Memory Summary',

    profile_lock_title: 'Global Profile Override',
    profile_lock_desc: 'Enable to use this profile across all worlds. Disable to use world-specific settings.',
    ph_name: 'Name',
    ph_avatar: 'Avatar URL',
    ph_gender: 'Gender',
    ph_age: 'Age',
    ph_bio: 'Likes / Bio',

    wb_home_desc: 'Overview',
    wb_btn_switch: 'Switch',
    wb_btn_meta: 'Info',
    wb_btn_char: 'Char',
    wb_btn_world: 'Lore',

    wb_switch_title: 'World Manager',
    wb_new_world: 'New Blank World',
    wb_del_confirm: 'Delete this world? Irreversible.',
    wb_export_world: 'Export World',
    wb_import_world: 'Import World',

    wb_char_player_mode: 'Player Mode',
    wb_char_use_global: 'Using Global Profile',
    wb_char_use_local: 'Using Local World Setting',

    wb_meta_name: 'World Name',
    wb_meta_tags: 'Tags',
    wb_meta_desc: 'Description',

    wb_char_ai_title: 'World NPC (Record)',
    wb_char_pl_title: 'Player Setting',

    store_offline: 'Store Offline',
    import_success: 'Success!',
    import_error: 'Format Error: Invalid WorldBook JSON',
    
    about_title: 'OmniTerminal',
    about_ver: 'v0.5.0 (Beta)',
    about_date: '2025.05.20',
  }
};

export const PRESET_THEMES: Record<string, Theme> = {
  simple: {
    type: 'smallpad_theme_v2',
    id: 'simple',
    name: '简',
    deviceType: 'Smart Pad',
    bg: 'bg-gray-50',
    deviceBorder: 'border-gray-800 bg-gray-900',
    wallpaper: 'bg-gradient-to-br from-indigo-50 via-white to-blue-50',
    appIconShape: 'rounded-2xl',
    statusBarText: 'text-slate-800',
    windowBg: 'bg-white/80 backdrop-blur-xl shadow-[0_8px_32px_rgba(0,0,0,0.1)] text-slate-800',
    inputBg: 'bg-white/80 border-gray-200 text-slate-800 shadow-sm',
    accentColor: 'bg-indigo-600',
    font: 'font-sans',
    codeBg: 'bg-gray-100 text-gray-800',
    labels: { battery: 'Power', signal: '5G', wifi: 'WiFi' }
  },
  dao: {
    type: 'smallpad_theme_v2',
    id: 'dao',
    name: '道',
    deviceType: 'Jade Tablet',
    bg: 'bg-[#e8f5e9]',
    deviceBorder: 'border-[#2e7d32] bg-[#1b5e20] ring-4 ring-[#a5d6a7]',
    wallpaper: 'bg-[url("https://www.transparenttextures.com/patterns/rice-paper-2.png")] bg-[#f1f8e9]',
    appIconShape: 'rounded-[20px] border-2 border-[#81c784]',
    statusBarText: 'text-[#1b5e20]',
    windowBg: 'bg-[#f1f8e9]/90 backdrop-blur-md border border-[#a5d6a7] shadow-[0_0_20px_rgba(46,125,50,0.15)] text-[#1b5e20]',
    inputBg: 'bg-[#e8f5e9]/80 border border-[#c8e6c9] text-[#1b5e20]',
    accentColor: 'bg-[#2e7d32]',
    font: 'font-serif',
    codeBg: 'bg-[#e8f5e9] border border-[#c8e6c9] text-[#2e7d32]',
    labels: { battery: 'Qi', signal: 'Spirit', wifi: 'Net' }
  },
  night: {
    type: 'smallpad_theme_v2',
    id: 'night',
    name: '夜',
    deviceType: 'Cyber Deck',
    bg: 'bg-[#050505]',
    deviceBorder: 'border-[#00bcd4] bg-black shadow-[0_0_25px_rgba(0,188,212,0.4)]',
    wallpaper: 'bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-slate-900 via-black to-black',
    appIconShape: 'rounded-sm border border-cyan-500/50 skew-x-[-6deg]',
    statusBarText: 'text-cyan-300',
    windowBg: 'bg-black/80 backdrop-blur-xl border border-cyan-500/30 shadow-[0_0_30px_rgba(0,188,212,0.15)] text-cyan-50',
    inputBg: 'bg-gray-900/60 border border-cyan-700/50 text-cyan-50 placeholder-cyan-800',
    accentColor: 'bg-cyan-600',
    font: 'font-mono',
    codeBg: 'bg-[#0a0a0a] border border-cyan-900 text-cyan-300',
    labels: { battery: 'PWR', signal: 'LINK', wifi: 'NET' }
  }
};
