import { Theme, AppConfig, World, AssistantConfig } from './types';

export const PRESET_THEMES: Record<string, Theme> = {
  simple: {
    id: 'simple',
    name: 'Simple',
    deviceType: 'Smart Pad',
    bg: 'bg-[#f2f2f7]',
    deviceBorder: 'bg-[#1c1c1e] border-[6px] border-[#2c2c2e]',
    wallpaper: 'bg-gradient-to-br from-[#ffffff] to-[#e5e5ea]',
    appIconShape: 'rounded-[18px]',
    statusBarText: 'text-[#1c1c1e]',
    windowBg: 'bg-[#ffffff]/95 backdrop-blur-xl shadow-2xl text-[#1c1c1e]',
    inputBg: 'bg-[#f2f2f7] border-transparent text-[#1c1c1e]',
    accentColor: 'text-[#007aff]',
    font: 'font-sans',
    codeBg: 'bg-[#f2f2f7]',
    labels: { battery: 'BAT', signal: '5G', wifi: 'WIFI' }
  },
  dao: {
    id: 'dao',
    name: 'Dao',
    deviceType: 'Jade Tablet',
    bg: 'bg-[#e8f5e9]',
    deviceBorder: 'bg-[#2e7d32] border-[6px] border-[#1b5e20] ring-2 ring-[#a5d6a7]',
    wallpaper: "bg-[url('https://www.transparenttextures.com/patterns/rice-paper-2.png')] bg-[#f1f8e9]",
    appIconShape: 'rounded-[20px] border-2 border-[#81c784]',
    statusBarText: 'text-[#1b5e20] drop-shadow-sm font-bold',
    windowBg: 'bg-[#f9fbe7]/95 backdrop-blur-md border border-[#c8e6c9] shadow-xl text-[#1b5e20]',
    inputBg: 'bg-[#ffffff]/60 border-[#a5d6a7] text-[#1b5e20]',
    accentColor: 'text-[#2e7d32]',
    font: 'font-serif',
    codeBg: 'bg-[#f1f8e9] border border-[#c8e6c9]',
    labels: { battery: 'Qi', signal: 'Link', wifi: 'Net' }
  },
  night: {
    id: 'night',
    name: 'Night',
    deviceType: 'Cyber Deck',
    bg: 'bg-[#09090b]',
    deviceBorder: 'bg-[#000000] border-[4px] border-[#333333] shadow-[0_0_20px_rgba(0,255,255,0.1)]',
    wallpaper: 'bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-[#1a1a1a] via-[#000000] to-[#000000]',
    appIconShape: 'rounded-xl border border-cyan-500/20',
    statusBarText: 'text-cyan-400 drop-shadow-[0_0_8px_rgba(34,211,238,0.6)]',
    windowBg: 'bg-[#0a0a0a]/90 backdrop-blur-xl border border-cyan-900/30 shadow-2xl text-cyan-50',
    inputBg: 'bg-[#121212] border-cyan-900/30 text-cyan-100 placeholder-cyan-800',
    accentColor: 'text-cyan-400',
    font: 'font-mono',
    codeBg: 'bg-[#000000] border border-cyan-900/50',
    labels: { battery: 'PWR', signal: 'SIG', wifi: 'NET' }
  }
};

export const DEFAULT_APP_CONFIG: AppConfig = {
  language: 'zh',
  theme: 'simple',
  provider: 'openai',
  apiKey: '',
  apiEndpoint: 'https://api.openai.com/v1',
  model: 'gpt-3.5-turbo',
  useGlobalProfile: true,
  userProfile: { name: 'Admin', uid: '10001', avatar: '', gender: '', age: '', likes: '' }
};

export const DEFAULT_WORLD: World = {
  id: 'default_world', 
  metadata: {
    name: 'Default World',
    author: 'System',
    tags: ['Assistant', 'Basic'],
    description: 'Factory default settings providing basic assistant services.',
    version: '1.0'
  },
  character: {
    name: 'No NPC',
    avatar: '',
    personality: '',
    greeting: ''
  },
  player: {
    name: 'User',
    avatar: '',
    bio: 'User' 
  },
  world: {
    lore: 'This is a virtual data space.',
    entries: [] 
  }
};

export const DEFAULT_ASSISTANT: AssistantConfig = {
    name: 'Omni',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=Omni',
    greeting: 'OmniTerminal initiated. I am your assistant "Omni".\n\nI can **analyze world views**, **roleplay**, or **assist with settings**. How may I help you?',
    systemPrompt: 'Your name is "Omni", an AI assistant built into the OmniTerminal. Your duty is to guide the user, answer questions, and assist in managing their WorldBooks. You are independent of any specific "WorldBook" story unless instructed otherwise. Use Markdown for formatting.'
};

export const I18N = {
  zh: {
    app_chat: 'OmniChat', 
    app_assistant: '万象助手',
    app_settings: '系统设置',
    app_store: '应用商城',
    app_worldbook: '万象书', 
    app_live: '万象直播',
    
    // Store & OS
    store_title: '应用中心',
    store_installed: '已安装',
    store_get: '获取',
    store_open: '打开',
    store_uninstall: '卸载',
    store_installing: '正在下载...',
    store_desc_live: '连接全网神经元，沉浸式 AI 直播互动平台。',
    store_desc_chat: '核心通讯模块，支持加密群聊与 AI 托管。',
    os_uninstall_confirm: '要卸载此应用吗？数据将被保留。',
    os_edit_mode_tip: '长按拖动图标进行排序',
    os_rotate: '旋转屏幕',
    os_uninstalling: '正在卸载...',
    cc_airplane: '飞行模式',
    cc_wifi: '无线网络',
    cc_bluetooth: '蓝牙',
    cc_rotate_lock: '方向锁定',
    cc_title: '控制中心',
    
    // Live
    live_tab_feed: '推荐',
    live_tab_dashboard: '工作台',
    live_tab_profile: '我的',
    live_start: '开始直播',
    live_setup_title: '创建直播间',
    live_topic: '直播主题',
    live_streamer: '主播设置',
    live_mode_me: '本人开播',
    live_mode_npc: 'AI 托管',
    live_haters: '黑粉模式',
    live_btn_start: '连接推流',
    live_end: '断开连接',
    live_chat_ph: '发送弹幕...',
    live_action_ph: '输入你的直播动作/语音内容...',
    live_host_label: '【主播动态】',
    live_stat_viewers: '在线',
    live_stat_coins: '收益',
    live_summary_title: '直播报告',
    live_highlights: '高光切片',
    live_duration: '时长',
    live_tips_npc: '正在转播 AI 信号流...',
    live_img_reaction: 'AI 观众正在解析图像信号...',
    live_dashboard_income: '总收益 (万象币)',
    live_dashboard_fans: '粉丝总量',
    live_dashboard_history: '直播记录',
    live_profile_edit: '编辑资料',
    live_profile_followers: '粉丝',
    live_profile_following: '关注',
    live_privacy_title: '隐私设置',
    live_privacy_public: '公开关注列表',
    live_privacy_search: '允许通过 ID 搜索',
    live_comments_title: '评论区',
    live_comment_ph: '善语结善缘...',
    live_share_title: '分享至',
    live_share_copy: '复制链接',
    live_share_chat: '转发给好友',
    live_copied: '链接已复制到剪贴板',
    live_follow: '关注',
    live_followed: '已关注',
    live_off_air: '未开播',
    live_likes: '点赞',
    live_comments: '评论',
    live_shares: '分享',
    live_studio: '创作者中心',
    live_streams: '场次',

    // Settings
    set_conn: '连接',
    set_anchor: '锚点', 
    set_theme: '主题', 
    set_profile: '档案',
    set_system: '系统',
    set_about: '关于',
    conn_title: '神经连接 (Neural Link)',
    conn_provider: '核心协议',
    conn_endpoint: '服务端点 (Endpoint)',
    conn_key: '访问密钥 (API Key)',
    conn_model: '模型标识 (Model ID)',
    conn_gemini_rec: '推荐: gemini-2.5-flash',
    conn_openai_desc: '兼容 OpenAI / DeepSeek / LocalAI',
    ast_config_title: '助手内核配置',
    ast_switch_title: '切换助手人格',
    ast_lib_default: '默认助手',
    ast_lib_world: '世界书角色导入',
    ast_name: '助手标识',
    ast_avatar: '视觉形态 (URL)',
    ast_prompt: '核心逻辑 (System Prompt)',
    ast_greeting: '唤醒语',
    ast_save_tip: '配置已更新',
    
    // System
    sys_manage: '数据管理',
    sys_app_manage: '应用管理',
    sys_reset: '初始化终端 (重置所有)',
    sys_export_all: '导出全局备份',
    sys_import_all: '恢复全局备份',
    sys_reset_confirm: '高危操作：确认初始化？',
    sys_reset_desc: '警告：此操作将清除所有数据（包括聊天记录、世界书、联系人），并将终端恢复至初始状态。',
    sys_import_confirm: '警告：导入将覆盖当前所有数据并刷新页面。确定继续？',
    
    // OmniChat Social
    oc_tab_msg: '消息',
    oc_tab_contact: '联系人',
    oc_tab_me: '我',
    oc_new_chat: '发起聊天',
    oc_create_group: '创建群聊',
    oc_add_friend: '添加/新建NPC',
    oc_group_name: '群聊名称',
    oc_group_notice: '群公告',
    oc_group_transfer: '转让群主',
    oc_group_members: '群成员',
    oc_group_setting: '群聊设置',
    oc_invite_member: '邀请成员',
    oc_remove_member: '移除',
    oc_btn_send: '发消息',
    oc_btn_edit: '编辑资料',
    oc_label_bio: '个性签名',
    oc_label_level: '等级',
    oc_label_uid: 'UID',
    oc_section_group: '群聊',
    oc_section_friend: '好友 / NPC',
    oc_placeholder_name: '请输入名称',
    oc_placeholder_prompt: '设定 NPC 的性格与记忆...',
    oc_save_contact: '保存设定',
    oc_delete_contact: '删除联系人',
    oc_leave_group: '退出群聊',
    oc_disband_group: '解散群聊',
    oc_select_contact: '选择联系人',
    oc_transfer_confirm: '确定将群主转让给该成员吗？',
    oc_share_target: '选择分享对象',
    
    // Common
    cmd_menu_title: '便捷指令',
    cmd_analyze: '当前世界分析',
    cmd_status: '终端状态自检',
    cmd_help: '操作指南',
    cmd_story: '剧情回顾',
    theme_simple: '简',
    theme_dao: '道',
    theme_night: '夜',
    theme_lang_switch: '系统语言 / Language',
    theme_installed: '已安装主题',
    theme_import: '导入 UI',
    theme_tpl: '下载模板',
    back: '返回',
    save: '保存',
    delete: '删除',
    create: '新建',
    import: '导入',
    export: '导出',
    online: '在线',
    typing: '对方正在输入...',
    summarizing: '正在整理记忆...',
    no_signal: '(无信号)',
    sys_tip_key: '(系统提示: 请在设置中配置 API Key)',
    msg_placeholder: '发消息...',
    img_upload_title: '发送图片',
    img_attached: '图片已选择',
    summary_label: '记忆摘要',
    chat_list_title: '消息',
    chat_official: '官方助手',
    chat_npc_suffix: ' (当前世界)',
    chat_new_msg: '[新消息]',
    chat_no_msg: '暂无消息',
    profile_lock_title: '全局档案覆盖',
    profile_lock_desc: '启用后，将强制使用下方档案作为所有世界的玩家设定。关闭则使用世界书自带设定。',
    ph_name: '姓名 / 昵称',
    ph_avatar: '头像链接 (URL)',
    ph_gender: '性别',
    ph_age: '年龄',
    ph_bio: '喜好 / 个性签名',
    ph_uid: '自定义 UID',
    wb_home_desc: '当前世界概览',
    wb_btn_switch: '切换',
    wb_btn_meta: '信息',
    wb_btn_char: '角色',
    wb_btn_world: '设定',
    wb_switch_title: '世界书管理',
    wb_new_world: '新建空白世界',
    wb_del_confirm: '确定要删除这个世界书吗？此操作不可逆。',
    wb_export_world: '导出世界书',
    wb_import_world: '导入世界书',
    wb_char_player_mode: '玩家设定模式',
    wb_char_use_global: '正在使用全局个人档案',
    wb_char_use_local: '正在使用当前世界独立设定',
    wb_meta_name: '世界名称',
    wb_meta_tags: '标签 (TAGs)',
    wb_meta_desc: '世界简介',
    wb_char_ai_title: '世界NPC (仅作记录)',
    wb_char_pl_title: '玩家设定 (Player)',
    store_offline: '商店暂未开放',
    import_success: '导入成功！',
    import_error: '格式错误：请确认文件符合万象书标准 (metadata/world/character)',
    about_title: '万界终端',
    about_ver: 'v0.5.4',
    about_date: '2025.05.26',
  },
  en: {
    app_chat: 'OmniChat',
    app_assistant: 'Omni Assistant',
    app_settings: 'Settings',
    app_store: 'App Store',
    app_worldbook: 'OmniBook',
    app_live: 'OmniLive',

    store_title: 'App Center',
    store_installed: 'Installed',
    store_get: 'Get',
    store_open: 'Open',
    store_uninstall: 'Uninstall',
    store_installing: 'Downloading...',
    store_desc_live: 'Immersive AI live streaming platform. Connect to the neural network.',
    store_desc_chat: 'Core communication module with encrypted group chats and AI hosting.',
    os_uninstall_confirm: 'Uninstall this app? Data will be kept.',
    os_edit_mode_tip: 'Long press and drag to sort icons',
    os_rotate: 'Rotate',
    os_uninstalling: 'Uninstalling...',
    cc_airplane: 'Airplane Mode',
    cc_wifi: 'Wi-Fi',
    cc_bluetooth: 'Bluetooth',
    cc_rotate_lock: 'Rotation Lock',
    cc_title: 'Control Center',

    live_tab_feed: 'Feed',
    live_tab_dashboard: 'Studio',
    live_tab_profile: 'Me',
    live_start: 'Go Live',
    live_setup_title: 'Stream Setup',
    live_topic: 'Topic',
    live_streamer: 'Streamer',
    live_mode_me: 'Me',
    live_mode_npc: 'NPC Host',
    live_haters: 'Allow Haters',
    live_btn_start: 'Start Stream',
    live_end: 'End Stream',
    live_chat_ph: 'Send Chat...',
    live_action_ph: 'Type your action or speech...',
    live_host_label: '[HOST]',
    live_stat_viewers: 'Viewers',
    live_stat_coins: 'Coins',
    live_summary_title: 'Stream Summary',
    live_highlights: 'AI Clips',
    live_duration: 'Duration',
    live_tips_npc: 'Relaying AI signal flow...',
    live_img_reaction: 'AI audience is reacting to image...',
    live_dashboard_income: 'Total Income',
    live_dashboard_fans: 'Followers',
    live_dashboard_history: 'History',
    live_profile_edit: 'Edit Profile',
    live_profile_followers: 'Followers',
    live_profile_following: 'Following',
    live_privacy_title: 'Privacy',
    live_privacy_public: 'Public Following List',
    live_privacy_search: 'Allow Search by UID',
    live_comments_title: 'Comments',
    live_comment_ph: 'Say something nice...',
    live_share_title: 'Share to',
    live_share_copy: 'Copy Link',
    live_share_chat: 'Forward to Chat',
    live_copied: 'Link copied to clipboard',
    live_follow: 'Follow',
    live_followed: 'Followed',
    live_off_air: 'OFF AIR',
    live_likes: 'Likes',
    live_comments: 'Comments',
    live_shares: 'Shares',
    live_studio: 'Creator Studio',
    live_streams: 'Streams',

    set_conn: 'Connect',
    set_anchor: 'Anchor',
    set_theme: 'Theme',
    set_profile: 'Profile',
    set_system: 'System',
    set_about: 'About',
    conn_title: 'Neural Link',
    conn_provider: 'Protocol',
    conn_endpoint: 'Endpoint',
    conn_key: 'API Key',
    conn_model: 'Model ID',
    conn_gemini_rec: 'Rec: gemini-2.5-flash',
    conn_openai_desc: 'OpenAI Compatible',
    ast_config_title: 'Core Configuration',
    ast_switch_title: 'Switch Persona',
    ast_lib_default: 'Default Omni',
    ast_lib_world: 'Import from WorldBook',
    ast_name: 'Name',
    ast_avatar: 'Avatar URL',
    ast_prompt: 'Core Logic',
    ast_greeting: 'Greeting',
    ast_save_tip: 'Config Updated',
    
    // System
    sys_manage: 'Data Management',
    sys_app_manage: 'App Management',
    sys_reset: 'Initialize Terminal',
    sys_export_all: 'Backup System',
    sys_import_all: 'Restore System',
    sys_reset_confirm: 'DANGER: Confirm Reset?',
    sys_reset_desc: 'WARNING: This will wipe ALL data (chats, worlds, contacts) and restore to default state.',
    sys_import_confirm: 'Warning: This will overwrite all data and reload. Continue?',

    // OmniChat Social
    oc_tab_msg: 'Chats',
    oc_tab_contact: 'Contacts',
    oc_tab_me: 'Me',
    oc_new_chat: 'New Chat',
    oc_create_group: 'Create Group',
    oc_add_friend: 'Add/Create NPC',
    oc_group_name: 'Group Name',
    oc_group_notice: 'Notice',
    oc_group_transfer: 'Transfer Owner',
    oc_group_members: 'Members',
    oc_group_setting: 'Group Settings',
    oc_invite_member: 'Invite Member',
    oc_remove_member: 'Remove',
    oc_btn_send: 'Message',
    oc_btn_edit: 'Edit Profile',
    oc_label_bio: 'Signature',
    oc_label_level: 'Level',
    oc_label_uid: 'UID',
    oc_section_group: 'Groups',
    oc_section_friend: 'Friends / NPCs',
    oc_placeholder_name: 'Enter Name',
    oc_placeholder_prompt: 'Personality & Memory...',
    oc_save_contact: 'Save Contact',
    oc_delete_contact: 'Delete Contact',
    oc_leave_group: 'Leave Group',
    oc_disband_group: 'Disband Group',
    oc_select_contact: 'Select Contact',
    oc_transfer_confirm: 'Transfer ownership to this member?',
    oc_share_target: 'Select Share Target',

    cmd_menu_title: 'Commands',
    cmd_analyze: 'Analyze World',
    cmd_status: 'System Check',
    cmd_help: 'User Guide',
    cmd_story: 'Recap Story',
    theme_simple: 'Simple',
    theme_dao: 'Dao',
    theme_night: 'Night',
    theme_lang_switch: 'Language / 语言',
    theme_installed: 'Installed Themes',
    theme_import: 'Import UI',
    theme_tpl: 'Template',
    back: 'Back',
    save: 'Save',
    delete: 'Delete',
    create: 'Create',
    import: 'Import',
    export: 'Export',
    online: 'Online',
    typing: 'Typing...',
    summarizing: 'Summarizing Memory...',
    no_signal: '(No Signal)',
    sys_tip_key: '(System: API Key missing)',
    msg_placeholder: 'Type a message...',
    img_upload_title: 'Send Image',
    img_attached: 'Image Selected',
    summary_label: 'Memory Summary',
    chat_list_title: 'Chats',
    chat_official: 'Official Assistant',
    chat_npc_suffix: ' (NPC)',
    chat_new_msg: '[New Message]',
    chat_no_msg: 'No messages yet',
    profile_lock_title: 'Global Profile Override',
    profile_lock_desc: 'Enable to use this profile across all worlds. Disable to use world-specific settings.',
    ph_name: 'Name',
    ph_avatar: 'Avatar URL',
    ph_gender: 'Gender',
    ph_age: 'Age',
    ph_bio: 'Likes / Bio',
    ph_uid: 'Custom UID',
    wb_home_desc: 'Overview',
    wb_btn_switch: 'Switch',
    wb_btn_meta: 'Info',
    wb_btn_char: 'Char',
    wb_btn_world: 'Lore',
    wb_switch_title: 'World Manager',
    wb_new_world: 'New Blank World',
    wb_del_confirm: 'Delete this world? Irreversible.',
    wb_export_world: 'Export World',
    wb_import_world: 'Import World',
    wb_char_player_mode: 'Player Mode',
    wb_char_use_global: 'Using Global Profile',
    wb_char_use_local: 'Using Local World Setting',
    wb_meta_name: 'World Name',
    wb_meta_tags: 'Tags',
    wb_meta_desc: 'Description',
    wb_char_ai_title: 'World NPC (Record)',
    wb_char_pl_title: 'Player Setting',
    store_offline: 'Store Offline',
    import_success: 'Success!',
    import_error: 'Format Error: Invalid WorldBook JSON',
    about_title: 'OmniTerminal',
    about_ver: 'v0.5.4',
    about_date: '2025.05.26',
  },
  ja: {
    app_chat: 'OmniChat', 
    app_assistant: '万象アシスタント',
    app_settings: 'システム設定',
    app_store: 'アプリストア',
    app_worldbook: '万象書', 
    app_live: '万象ライブ',
    
    store_title: 'アプリセンター',
    store_installed: 'インストール済',
    store_get: '入手',
    store_open: '開く',
    store_uninstall: 'アンインストール',
    store_installing: 'ダウンロード中...',
    store_desc_live: '没入型AIライブ配信プラットフォーム。',
    store_desc_chat: '暗号化グループチャットとAIホスティングを備えた通信モジュール。',
    os_uninstall_confirm: 'このアプリをアンインストールしますか？データは保持されます。',
    os_edit_mode_tip: 'アイコンを長押ししてドラッグで並び替え',
    os_rotate: '回転',
    os_uninstalling: 'アンインストール中...',
    cc_airplane: '機内モード',
    cc_wifi: 'Wi-Fi',
    cc_bluetooth: 'Bluetooth',
    cc_rotate_lock: '画面ロック',
    cc_title: 'コントロールセンター',

    live_tab_feed: 'おすすめ',
    live_tab_dashboard: 'スタジオ',
    live_tab_profile: 'マイページ',
    live_start: '配信開始',
    live_setup_title: '配信設定',
    live_topic: 'タイトル',
    live_streamer: '配信者',
    live_mode_me: '自分',
    live_mode_npc: 'NPC任せ',
    live_haters: 'アンチ許可',
    live_btn_start: '配信開始',
    live_end: '配信終了',
    live_chat_ph: 'コメント送信...',
    live_action_ph: '行動やセリフを入力...',
    live_host_label: '【配信主】',
    live_stat_viewers: '視聴者',
    live_stat_coins: 'コイン',
    live_summary_title: '配信リザルト',
    live_highlights: 'AI切り抜き',
    live_duration: '時間',
    live_tips_npc: 'AI信号を中継中...',
    live_img_reaction: 'AI視聴者が画像を見ています...',
    live_dashboard_income: '総収益',
    live_dashboard_fans: 'フォロワー',
    live_dashboard_history: '配信履歴',
    live_profile_edit: '編集',
    live_profile_followers: 'フォロワー',
    live_profile_following: 'フォロー',
    live_privacy_title: 'プライバシー',
    live_privacy_public: 'フォローリスト公開',
    live_privacy_search: 'ID検索を許可',
    live_comments_title: 'コメント',
    live_comment_ph: '優しいコメントを...',
    live_share_title: 'シェア',
    live_share_copy: 'リンクをコピー',
    live_share_chat: 'チャットに転送',
    live_copied: 'リンクをコピーしました',
    live_follow: 'フォロー',
    live_followed: 'フォロー中',
    live_off_air: '未放送',
    live_likes: 'いいね',
    live_comments: 'コメント',
    live_shares: 'シェア',
    live_studio: 'クリエイターツール',
    live_streams: '配信数',

    // Settings
    set_conn: '接続',
    set_anchor: 'アンカー', 
    set_theme: 'テーマ', 
    set_profile: 'プロフ',
    set_system: 'システム',
    set_about: '情報',
    conn_title: 'ニューラルリンク (Neural Link)',
    conn_provider: 'コアプロトコル',
    conn_endpoint: 'エンドポイント (Endpoint)',
    conn_key: 'アクセスキー (API Key)',
    conn_model: 'モデルID (Model ID)',
    conn_gemini_rec: '推奨: gemini-2.5-flash',
    conn_openai_desc: 'OpenAI / DeepSeek / LocalAI 互換',
    ast_config_title: 'アシスタント設定',
    ast_switch_title: '人格切り替え',
    ast_lib_default: 'デフォルト万象',
    ast_lib_world: '万象書からインポート',
    ast_name: '名前',
    ast_avatar: 'アバター (URL)',
    ast_prompt: 'システムプロンプト',
    ast_greeting: '挨拶',
    ast_save_tip: '設定を保存しました',
    
    // System
    sys_manage: 'データ管理',
    sys_app_manage: 'アプリ管理',
    sys_reset: '端末初期化',
    sys_export_all: 'バックアップ作成',
    sys_import_all: 'バックアップ復元',
    sys_reset_confirm: '危険：初期化しますか？',
    sys_reset_desc: '警告：すべてのデータ（チャット、世界書、連絡先）が消去され、初期状態に戻ります。',
    sys_import_confirm: '警告：現在のデータが上書きされます。再読み込みしますか？',
    
    // OmniChat Social
    oc_tab_msg: 'チャット',
    oc_tab_contact: '連絡先',
    oc_tab_me: 'マイページ',
    oc_new_chat: '新規チャット',
    oc_create_group: 'グループ作成',
    oc_add_friend: 'NPC追加/作成',
    oc_group_name: 'グループ名',
    oc_group_notice: 'アナウンス',
    oc_group_transfer: '管理者譲渡',
    oc_group_members: 'メンバー',
    oc_group_setting: 'グループ設定',
    oc_invite_member: 'メンバー招待',
    oc_remove_member: '追放',
    oc_btn_send: '送信',
    oc_btn_edit: '編集',
    oc_label_bio: 'ひとこと',
    oc_label_level: 'レベル',
    oc_label_uid: 'UID',
    oc_section_group: 'グループ',
    oc_section_friend: 'フレンド / NPC',
    oc_placeholder_name: '名前を入力',
    oc_placeholder_prompt: 'NPCの性格と記憶を設定...',
    oc_save_contact: '保存',
    oc_delete_contact: '削除',
    oc_leave_group: '退出',
    oc_disband_group: '解散',
    oc_select_contact: '連絡先を選択',
    oc_transfer_confirm: '管理者を譲渡しますか？',
    oc_share_target: '共有先を選択',
    
    // Common
    cmd_menu_title: 'ショートカット',
    cmd_analyze: '世界分析',
    cmd_status: '状態チェック',
    cmd_help: 'ヘルプ',
    cmd_story: 'ストーリー回想',
    theme_simple: 'シンプル',
    theme_dao: '道 (Dao)',
    theme_night: 'ナイト',
    theme_lang_switch: '言語 / Language',
    theme_installed: 'インストール済み',
    theme_import: 'インポート',
    theme_tpl: 'テンプレ',
    back: '戻る',
    save: '保存',
    delete: '削除',
    create: '作成',
    import: 'インポート',
    export: 'エクスポート',
    online: 'オンライン',
    typing: '入力中...',
    summarizing: '記憶整理中...',
    no_signal: '(信号なし)',
    sys_tip_key: '(システム: API Keyを設定してください)',
    msg_placeholder: 'メッセージを入力...',
    img_upload_title: '画像送信',
    img_attached: '画像選択済み',
    summary_label: '記憶要約',
    chat_list_title: 'チャット',
    chat_official: '公式アシスタント',
    chat_npc_suffix: ' (NPC)',
    chat_new_msg: '[新着]',
    chat_no_msg: 'メッセージなし',
    profile_lock_title: 'グローバル設定上書き',
    profile_lock_desc: '有効にすると、すべての世界でこのプロフィールが使用されます。無効にすると世界書の設定が使用されます。',
    ph_name: '名前',
    ph_avatar: 'アバターURL',
    ph_gender: '性別',
    ph_age: '年齢',
    ph_bio: '自己紹介 / 署名',
    ph_uid: 'カスタム UID',
    wb_home_desc: '概要',
    wb_btn_switch: '切替',
    wb_btn_meta: '情報',
    wb_btn_char: 'キャラ',
    wb_btn_world: '設定',
    wb_switch_title: '世界書管理',
    wb_new_world: '新規作成',
    wb_del_confirm: '削除しますか？この操作は取り消せません。',
    wb_export_world: 'エクスポート',
    wb_import_world: 'インポート',
    wb_char_player_mode: 'プレイヤー設定モード',
    wb_char_use_global: 'グローバル設定を使用中',
    wb_char_use_local: '世界独自の設定を使用中',
    wb_meta_name: '世界名',
    wb_meta_tags: 'タグ',
    wb_meta_desc: '説明',
    wb_char_ai_title: '世界NPC (記録用)',
    wb_char_pl_title: 'プレイヤー設定',
    store_offline: 'ストアオフライン',
    import_success: '成功！',
    import_error: 'フォーマットエラー',
    about_title: 'OmniTerminal',
    about_ver: 'v0.5.4',
    about_date: '2025.05.26',
  }
};