import { Theme } from './types';

export const I18N = {
  zh: {
    app_chat: 'OmniChat', 
    app_assistant: '万象助手',
    app_settings: '系统设置',
    app_store: '应用商店',
    app_worldbook: '万象书', 
    
    // Settings
    set_conn: '连接',
    set_anchor: '锚点', 
    set_theme: '主题', 
    set_profile: '档案',
    set_system: '系统',
    set_about: '关于',
    conn_title: '神经连接 (Neural Link)',
    conn_provider: '核心协议',
    conn_endpoint: '服务端点 (Endpoint)',
    conn_key: '访问密钥 (API Key)',
    conn_model: '模型标识 (Model ID)',
    conn_gemini_rec: '推荐: gemini-2.5-flash',
    conn_openai_desc: '兼容 OpenAI / DeepSeek / LocalAI',
    ast_config_title: '助手内核配置',
    ast_switch_title: '切换助手人格',
    ast_lib_default: '默认助手',
    ast_lib_world: '世界书角色导入',
    ast_name: '助手标识',
    ast_avatar: '视觉形态 (URL)',
    ast_prompt: '核心逻辑 (System Prompt)',
    ast_greeting: '唤醒语',
    ast_save_tip: '配置已更新',
    
    // System
    sys_manage: '数据管理',
    sys_reset: '初始化重置',
    sys_export_all: '导出全局备份',
    sys_import_all: '恢复全局备份',
    sys_reset_confirm: '警告：此操作将清除所有聊天记录、世界书和设置。确定要初始化吗？',
    sys_import_confirm: '警告：导入将覆盖当前所有数据并刷新页面。确定继续？',
    
    // OmniChat Social
    oc_tab_msg: '消息',
    oc_tab_contact: '联系人',
    oc_tab_me: '我',
    oc_new_chat: '发起聊天',
    oc_create_group: '创建群聊',
    oc_add_friend: '添加/新建NPC',
    oc_group_name: '群聊名称',
    oc_group_notice: '群公告',
    oc_group_transfer: '转让群主',
    oc_group_members: '群成员',
    oc_group_setting: '群聊设置',
    oc_invite_member: '邀请成员',
    oc_remove_member: '移除',
    oc_btn_send: '发消息',
    oc_btn_edit: '编辑资料',
    oc_label_bio: '个性签名',
    oc_label_level: '等级',
    oc_label_uid: 'UID',
    oc_section_group: '群聊',
    oc_section_friend: '好友 / NPC',
    oc_placeholder_name: '请输入名称',
    oc_placeholder_prompt: '设定 NPC 的性格与记忆...',
    oc_save_contact: '保存设定',
    oc_delete_contact: '删除联系人',
    oc_leave_group: '退出群聊',
    oc_disband_group: '解散群聊',
    oc_select_contact: '选择联系人',
    oc_transfer_confirm: '确定将群主转让给该成员吗？',
    
    // Common
    cmd_menu_title: '便捷指令',
    cmd_analyze: '当前世界分析',
    cmd_status: '终端状态自检',
    cmd_help: '操作指南',
    cmd_story: '剧情回顾',
    theme_simple: '简',
    theme_dao: '道',
    theme_night: '夜',
    theme_lang_switch: '系统语言 / Language',
    theme_installed: '已安装主题',
    theme_import: '导入 UI',
    theme_tpl: '下载模板',
    back: '返回',
    save: '保存',
    delete: '删除',
    create: '新建',
    import: '导入',
    export: '导出',
    online: '在线',
    typing: '对方正在输入...',
    summarizing: '正在整理记忆...',
    no_signal: '(无信号)',
    sys_tip_key: '(系统提示: 请在设置中配置 API Key)',
    msg_placeholder: '发消息...',
    img_upload_title: '发送图片',
    img_attached: '图片已选择',
    summary_label: '记忆摘要',
    chat_list_title: '消息',
    chat_official: '官方助手',
    chat_npc_suffix: ' (当前世界)',
    chat_new_msg: '[新消息]',
    chat_no_msg: '暂无消息',
    profile_lock_title: '全局档案覆盖',
    profile_lock_desc: '启用后，将强制使用下方档案作为所有世界的玩家设定。关闭则使用世界书自带设定。',
    ph_name: '姓名 / 昵称',
    ph_avatar: '头像链接 (URL)',
    ph_gender: '性别',
    ph_age: '年龄',
    ph_bio: '喜好 / 个性签名',
    ph_uid: '自定义 UID',
    wb_home_desc: '当前世界概览',
    wb_btn_switch: '切换',
    wb_btn_meta: '信息',
    wb_btn_char: '角色',
    wb_btn_world: '设定',
    wb_switch_title: '世界书管理',
    wb_new_world: '新建空白世界',
    wb_del_confirm: '确定要删除这个世界书吗？此操作不可逆。',
    wb_export_world: '导出世界书',
    wb_import_world: '导入世界书',
    wb_char_player_mode: '玩家设定模式',
    wb_char_use_global: '正在使用全局个人档案',
    wb_char_use_local: '正在使用当前世界独立设定',
    wb_meta_name: '世界名称',
    wb_meta_tags: '标签 (TAGs)',
    wb_meta_desc: '世界简介',
    wb_char_ai_title: '世界NPC (仅作记录)',
    wb_char_pl_title: '玩家设定 (Player)',
    store_offline: '商店暂未开放',
    import_success: '导入成功！',
    import_error: '格式错误：请确认文件符合万象书标准 (metadata/world/character)',
    about_title: '万界终端',
    about_ver: 'v0.5.2',
    about_date: '2025.05.25',
  },
  en: {
    app_chat: 'OmniChat',
    app_assistant: 'Omni Assistant',
    app_settings: 'Settings',
    app_store: 'Store',
    app_worldbook: 'OmniBook',

    set_conn: 'Connect',
    set_anchor: 'Anchor',
    set_theme: 'Theme',
    set_profile: 'Profile',
    set_system: 'System',
    set_about: 'About',
    conn_title: 'Neural Link',
    conn_provider: 'Protocol',
    conn_endpoint: 'Endpoint',
    conn_key: 'API Key',
    conn_model: 'Model ID',
    conn_gemini_rec: 'Rec: gemini-2.5-flash',
    conn_openai_desc: 'OpenAI Compatible',
    ast_config_title: 'Core Configuration',
    ast_switch_title: 'Switch Persona',
    ast_lib_default: 'Default Omni',
    ast_lib_world: 'Import from WorldBook',
    ast_name: 'Name',
    ast_avatar: 'Avatar URL',
    ast_prompt: 'Core Logic',
    ast_greeting: 'Greeting',
    ast_save_tip: 'Config Updated',
    
    // System
    sys_manage: 'Data Management',
    sys_reset: 'Factory Reset',
    sys_export_all: 'Backup System',
    sys_import_all: 'Restore System',
    sys_reset_confirm: 'Warning: This will erase ALL data. Continue?',
    sys_import_confirm: 'Warning: This will overwrite all data and reload. Continue?',

    // OmniChat Social
    oc_tab_msg: 'Chats',
    oc_tab_contact: 'Contacts',
    oc_tab_me: 'Me',
    oc_new_chat: 'New Chat',
    oc_create_group: 'Create Group',
    oc_add_friend: 'Add/Create NPC',
    oc_group_name: 'Group Name',
    oc_group_notice: 'Notice',
    oc_group_transfer: 'Transfer Owner',
    oc_group_members: 'Members',
    oc_group_setting: 'Group Settings',
    oc_invite_member: 'Invite Member',
    oc_remove_member: 'Remove',
    oc_btn_send: 'Message',
    oc_btn_edit: 'Edit Profile',
    oc_label_bio: 'Signature',
    oc_label_level: 'Level',
    oc_label_uid: 'UID',
    oc_section_group: 'Groups',
    oc_section_friend: 'Friends / NPCs',
    oc_placeholder_name: 'Enter Name',
    oc_placeholder_prompt: 'Personality & Memory...',
    oc_save_contact: 'Save Contact',
    oc_delete_contact: 'Delete Contact',
    oc_leave_group: 'Leave Group',
    oc_disband_group: 'Disband Group',
    oc_select_contact: 'Select Contact',
    oc_transfer_confirm: 'Transfer ownership to this member?',

    cmd_menu_title: 'Commands',
    cmd_analyze: 'Analyze World',
    cmd_status: 'System Check',
    cmd_help: 'User Guide',
    cmd_story: 'Recap Story',
    theme_simple: 'Simple',
    theme_dao: 'Dao',
    theme_night: 'Night',
    theme_lang_switch: 'Language / 语言',
    theme_installed: 'Installed Themes',
    theme_import: 'Import UI',
    theme_tpl: 'Template',
    back: 'Back',
    save: 'Save',
    delete: 'Delete',
    create: 'Create',
    import: 'Import',
    export: 'Export',
    online: 'Online',
    typing: 'Typing...',
    summarizing: 'Summarizing Memory...',
    no_signal: '(No Signal)',
    sys_tip_key: '(System: API Key missing)',
    msg_placeholder: 'Type a message...',
    img_upload_title: 'Send Image',
    img_attached: 'Image Selected',
    summary_label: 'Memory Summary',
    chat_list_title: 'Chats',
    chat_official: 'Official Assistant',
    chat_npc_suffix: ' (NPC)',
    chat_new_msg: '[New Message]',
    chat_no_msg: 'No messages yet',
    profile_lock_title: 'Global Profile Override',
    profile_lock_desc: 'Enable to use this profile across all worlds. Disable to use world-specific settings.',
    ph_name: 'Name',
    ph_avatar: 'Avatar URL',
    ph_gender: 'Gender',
    ph_age: 'Age',
    ph_bio: 'Likes / Bio',
    ph_uid: 'Custom UID',
    wb_home_desc: 'Overview',
    wb_btn_switch: 'Switch',
    wb_btn_meta: 'Info',
    wb_btn_char: 'Char',
    wb_btn_world: 'Lore',
    wb_switch_title: 'World Manager',
    wb_new_world: 'New Blank World',
    wb_del_confirm: 'Delete this world? Irreversible.',
    wb_export_world: 'Export World',
    wb_import_world: 'Import World',
    wb_char_player_mode: 'Player Mode',
    wb_char_use_global: 'Using Global Profile',
    wb_char_use_local: 'Using Local World Setting',
    wb_meta_name: 'World Name',
    wb_meta_tags: 'Tags',
    wb_meta_desc: 'Description',
    wb_char_ai_title: 'World NPC (Record)',
    wb_char_pl_title: 'Player Setting',
    store_offline: 'Store Offline',
    import_success: 'Success!',
    import_error: 'Format Error: Invalid WorldBook JSON',
    about_title: 'OmniTerminal',
    about_ver: 'v0.5.2',
    about_date: '2025.05.25',
  },
  ja: {
    app_chat: 'OmniChat', 
    app_assistant: '万象アシスタント',
    app_settings: 'システム設定',
    app_store: 'アプリストア',
    app_worldbook: '万象書', 
    
    // Settings
    set_conn: '接続',
    set_anchor: 'アンカー', 
    set_theme: 'テーマ', 
    set_profile: 'プロフ',
    set_system: 'システム',
    set_about: '情報',
    conn_title: 'ニューラルリンク (Neural Link)',
    conn_provider: 'コアプロトコル',
    conn_endpoint: 'エンドポイント (Endpoint)',
    conn_key: 'アクセスキー (API Key)',
    conn_model: 'モデルID (Model ID)',
    conn_gemini_rec: '推奨: gemini-2.5-flash',
    conn_openai_desc: 'OpenAI / DeepSeek / LocalAI 互換',
    ast_config_title: 'アシスタント設定',
    ast_switch_title: '人格切り替え',
    ast_lib_default: 'デフォルト万象',
    ast_lib_world: '万象書からインポート',
    ast_name: '名前',
    ast_avatar: 'アバター (URL)',
    ast_prompt: 'システムプロンプト',
    ast_greeting: '挨拶',
    ast_save_tip: '設定を保存しました',
    
    // System
    sys_manage: 'データ管理',
    sys_reset: '初期化',
    sys_export_all: 'バックアップ作成',
    sys_import_all: 'バックアップ復元',
    sys_reset_confirm: '警告：すべてのデータが消去されます。続行しますか？',
    sys_import_confirm: '警告：現在のデータが上書きされます。再読み込みしますか？',
    
    // OmniChat Social
    oc_tab_msg: 'チャット',
    oc_tab_contact: '連絡先',
    oc_tab_me: 'マイページ',
    oc_new_chat: '新規チャット',
    oc_create_group: 'グループ作成',
    oc_add_friend: 'NPC追加/作成',
    oc_group_name: 'グループ名',
    oc_group_notice: 'アナウンス',
    oc_group_transfer: '管理者譲渡',
    oc_group_members: 'メンバー',
    oc_group_setting: 'グループ設定',
    oc_invite_member: 'メンバー招待',
    oc_remove_member: '追放',
    oc_btn_send: '送信',
    oc_btn_edit: '編集',
    oc_label_bio: 'ひとこと',
    oc_label_level: 'レベル',
    oc_label_uid: 'UID',
    oc_section_group: 'グループ',
    oc_section_friend: 'フレンド / NPC',
    oc_placeholder_name: '名前を入力',
    oc_placeholder_prompt: 'NPCの性格と記憶を設定...',
    oc_save_contact: '保存',
    oc_delete_contact: '削除',
    oc_leave_group: '退出',
    oc_disband_group: '解散',
    oc_select_contact: '連絡先を選択',
    oc_transfer_confirm: '管理者を譲渡しますか？',
    
    // Common
    cmd_menu_title: 'ショートカット',
    cmd_analyze: '世界分析',
    cmd_status: '状態チェック',
    cmd_help: 'ヘルプ',
    cmd_story: 'ストーリー回想',
    theme_simple: 'シンプル',
    theme_dao: '道 (Dao)',
    theme_night: 'ナイト',
    theme_lang_switch: '言語 / Language',
    theme_installed: 'インストール済み',
    theme_import: 'インポート',
    theme_tpl: 'テンプレ',
    back: '戻る',
    save: '保存',
    delete: '削除',
    create: '作成',
    import: 'インポート',
    export: 'エクスポート',
    online: 'オンライン',
    typing: '入力中...',
    summarizing: '記憶整理中...',
    no_signal: '(信号なし)',
    sys_tip_key: '(システム: API Keyを設定してください)',
    msg_placeholder: 'メッセージを入力...',
    img_upload_title: '画像送信',
    img_attached: '画像選択済み',
    summary_label: '記憶要約',
    chat_list_title: 'チャット',
    chat_official: '公式アシスタント',
    chat_npc_suffix: ' (NPC)',
    chat_new_msg: '[新着]',
    chat_no_msg: 'メッセージなし',
    profile_lock_title: 'グローバル設定上書き',
    profile_lock_desc: '有効にすると、すべての世界でこのプロフィールが使用されます。無効にすると世界書の設定が使用されます。',
    ph_name: '名前',
    ph_avatar: 'アバターURL',
    ph_gender: '性別',
    ph_age: '年齢',
    ph_bio: '自己紹介 / 署名',
    ph_uid: 'カスタム UID',
    wb_home_desc: '概要',
    wb_btn_switch: '切替',
    wb_btn_meta: '情報',
    wb_btn_char: 'キャラ',
    wb_btn_world: '設定',
    wb_switch_title: '世界書管理',
    wb_new_world: '新規作成',
    wb_del_confirm: '削除しますか？この操作は取り消せません。',
    wb_export_world: 'エクスポート',
    wb_import_world: 'インポート',
    wb_char_player_mode: 'プレイヤー設定モード',
    wb_char_use_global: 'グローバル設定を使用中',
    wb_char_use_local: '世界独自の設定を使用中',
    wb_meta_name: '世界名',
    wb_meta_tags: 'タグ',
    wb_meta_desc: '説明',
    wb_char_ai_title: '世界NPC (記録用)',
    wb_char_pl_title: 'プレイヤー設定',
    store_offline: 'ストアオフライン',
    import_success: '成功！',
    import_error: 'フォーマットエラー',
    about_title: 'OmniTerminal',
    about_ver: 'v0.5.2',
    about_date: '2025.05.25',
  }
};

export const PRESET_THEMES: Record<string, Theme> = {
  simple: {
    type: 'smallpad_theme_v2',
    id: 'simple',
    name: '简',
    deviceType: 'Smart Pad',
    bg: 'bg-gray-50',
    deviceBorder: 'border-gray-800 bg-gray-900',
    wallpaper: 'bg-gradient-to-br from-indigo-50 via-white to-blue-50',
    appIconShape: 'rounded-2xl',
    statusBarText: 'text-slate-800',
    windowBg: 'bg-white/95 backdrop-blur-xl shadow-[0_8px_32px_rgba(0,0,0,0.1)] text-slate-800',
    inputBg: 'bg-gray-100 border-transparent text-slate-800 focus:bg-white focus:border-indigo-200 focus:shadow-sm',
    accentColor: 'bg-indigo-600',
    font: 'font-sans',
    codeBg: 'bg-gray-100 text-gray-800',
    labels: { battery: 'Power', signal: '5G', wifi: 'WiFi' }
  },
  dao: {
    type: 'smallpad_theme_v2',
    id: 'dao',
    name: '道',
    deviceType: 'Jade Tablet',
    bg: 'bg-[#e8f5e9]',
    deviceBorder: 'border-[#2e7d32] bg-[#1b5e20] ring-4 ring-[#a5d6a7]',
    wallpaper: 'bg-[url("https://www.transparenttextures.com/patterns/rice-paper-2.png")] bg-[#f1f8e9]',
    appIconShape: 'rounded-[20px] border-2 border-[#81c784]',
    statusBarText: 'text-[#1b5e20]',
    windowBg: 'bg-[#f1f8e9]/95 backdrop-blur-md border border-[#a5d6a7] shadow-[0_0_20px_rgba(46,125,50,0.15)] text-[#1b5e20]',
    inputBg: 'bg-[#e8f5e9] border border-[#c8e6c9] text-[#1b5e20] focus:bg-[#f9fbe7]',
    accentColor: 'bg-[#2e7d32]',
    font: 'font-serif',
    codeBg: 'bg-[#e8f5e9] border border-[#c8e6c9] text-[#2e7d32]',
    labels: { battery: 'Qi', signal: 'Spirit', wifi: 'Net' }
  },
  night: {
    type: 'smallpad_theme_v2',
    id: 'night',
    name: '夜',
    deviceType: 'Cyber Deck',
    bg: 'bg-[#050505]',
    deviceBorder: 'border-[#00bcd4] bg-black shadow-[0_0_25px_rgba(0,188,212,0.4)]',
    wallpaper: 'bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-slate-900 via-black to-black',
    appIconShape: 'rounded-sm border border-cyan-500/50 skew-x-[-6deg]',
    statusBarText: 'text-cyan-300',
    windowBg: 'bg-black/90 backdrop-blur-xl border border-cyan-500/30 shadow-[0_0_30px_rgba(0,188,212,0.15)] text-cyan-50',
    inputBg: 'bg-gray-900/60 border border-cyan-900/50 text-cyan-50 placeholder-cyan-800 focus:bg-gray-900 focus:border-cyan-500/50',
    accentColor: 'bg-cyan-600',
    font: 'font-mono',
    codeBg: 'bg-[#0a0a0a] border border-cyan-900 text-cyan-300',
    labels: { battery: 'PWR', signal: 'LINK', wifi: 'NET' }
  }
};